#! /bin/sh

# This script builds and installs libxml2, libxslt and lxml in the agent directory.
#
# Building a recent version of libxml2 rather than using one used with the system
# can be required to workaround the bug #347316 of libxml2. Some distributions 
# like RHEL 5 still haven't backported the patch in their RPMs. 
#
#
# Shared libraries (.so files) are installed in the agent directory
# Python lxml package is installed in the agent directory too
#
# To use theses libraries/packages instead of the system ones, the fix_libxml2 
# wrapper must be used

function fail {
	echo "$1"
	exit 1
}

echo ""
echo "This script automatically builds and bundles libxml2, libxslt and lxml into the ProActive Linux Agent to circumvent bug #347316 in old libxml2 releases."
echo ""
echo "To be able to build theses packages following packages must be installed (exact names depend of your distribution)"
echo "  - gcc"
echo "  - libtool"
echo "  - python-devel"
echo "  - zlib-devel"

sleep 10 

D_AGENT=$(readlink -e $(dirname $0))
D_TMP=$(mktemp -d)

VER_LIBXML2=libxml2-2.7.8
URL_LIBXML2=ftp://xmlsoft.org/libxml2/${VER_LIBXML2}.tar.gz

VER_LIBXSLT=libxslt-1.1.26
URL_LIBXSLT=ftp://xmlsoft.org/libxml2/${VER_LIBXSLT}.tar.gz

VER_LXML=lxml-2.2.8
URL_LXML=http://codespeak.net/lxml/${VER_LXML}.tgz

cd ${D_TMP}

wget ${URL_LIBXML2} || fail "Failed to download ${URL_LIBXML2}"
wget ${URL_LIBXSLT} || fail "Failed to download ${URL_LIBXSLT}"
wget ${URL_LXML} || fail "Faild to download ${URL_LXML}"

mkdir ${D_TMP}/libxml2
tar xvfz ${VER_LIBXML2}.tar.gz
cd ${D_TMP}/${VER_LIBXML2} 
./configure --prefix=${D_TMP}/libxml2 || fail "Failed to configure ${VER_LIBXML2}"
make || fail "Failed to build ${VER_LIBXML2}"
make install || fail "Failed to install ${VER_LIBXML2}"

mkdir ${D_TMP}/libxslt
cd ${D_TMP}
tar xvfz ${VER_LIBXSLT}.tar.gz
cd ${D_TMP}/${VER_LIBXSLT}
./configure --prefix=${D_TMP}/libxslt --with-libxml-prefix=${D_TMP}/libxml2 || fail "Failed to configure ${VER_LIBXSLT}"
make || fail "Failed to build ${VER_LIBXSLT}"
make install || fail "Failed to install ${VER_LIBXSLT}"

cd ${D_TMP}
tar xvfz ${VER_LXML}.tgz
cd ${D_TMP}/${VER_LXML}
python setup.py bdist --with-xslt-config=${D_TMP}/libxslt/bin/xslt-config
cd dist
tar xvfz lxml*.tar.gz
cp -r $(find . -type d -name "lxml") ${D_TMP}/lxml

cp ${D_TMP}/libxml2/lib/*.so* ${D_AGENT} || fail "Failed to bundle libxml2"
cp ${D_TMP}/libxslt/lib/*.so* ${D_AGENT} || fail "Failed to bundle libxslt"
cp -r ${D_TMP}/lxml ${D_AGENT} || fail "Failed to bundle lxml" 

echo ""
echo ""
echo "  ->> Successfully installed libxml2, libxslt and lxml in the agent directory"
rm -R ${D_TMP}
