#!/bin/bash
#
# chkconfig: 35 90 12
# description: ProActive Linux Agent
#

# Get function from functions library
. /etc/init.d/functions

# Start the ProActive Linux Agent
start() {
        initlog -c "echo -n Starting the ProActive Linux Agent: "
        /home/vasile/workspacePA/linux-agent/pa-agent &
        ### Create the lock file ###
        touch /var/lock/subsys/pa-agent.lock
        success $"ProActive Linux Agent startup"
        echo
}

# Restart the service FOO
stop() {
        initlog -c "echo -n Stopping the ProActive Linux Agent: "
        killproc pa-agent
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/pa-agent.lock
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0