#!/bin/bash
#
# proactive-agent	Start up the ProActive Linux Agent
# chkconfig: 2345 95 05
# description: Start up a ProActive agent
#
# processname: proactive-agent
# config: /etc/proactive/agent.config
# config: /etc/sysconfig/proactive-agent
# pidfile: /var/run/proactive-agent.pid

### BEGIN INIT INFO
# Provides: proactive-agent
# Required-Start: $local_fs $network 
# Required-Stop: $local_fs 
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the ProActive Linux Agent
# Description:       ProActive Linux Agent starts ProActive runtimes according to a schedule
### END INIT INFO



# source function library
. /etc/rc.d/init.d/functions

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

# default values
PROG="/usr/bin/proactive-agent"
LOGFILE="/var/log/proactive-agent/agent.log"
AGENTOPTS="-d"
AGENTUSER="paagent"
AGENTGROUP="paagent"
CONFFILE="/etc/proactive/agent.xml"
AGENTHOME="/var/lib/proactive-agent"

# source the config
. /etc/sysconfig/proactive-agent

RETVAL=0

case "$1" in
  start)
	echo -n $"Starting proactive-agent: "
	if [ ! -e $AGENTHOME/cgroups/tasks ] ; then
		mount -t cgroup -o memory proactive-agent $AGENTHOME/cgroups
		cgcreate -t $AGENTUSER:$AGENTGROUP -a $AGENTUSER:$AGENTGROUP -g memory:/agent
	fi 

	/sbin/runuser -s /bin/sh -c "$PROG --logFile $LOGFILE $AGENTOPTS $CONFFILE" $AGENTUSER >> $LOGFILE.stdout 2>&1 &
	disown -ar
	/bin/touch /var/lock/subsys/proactive-agent
	/bin/usleep 500000
	status proactive-agent &> /dev/null && echo_success || echo_failure
	RETVAL=$?
	if [ $RETVAL -eq 0 ]; then
		/bin/touch /var/lock/subsys/proactive-agent
		/sbin/pidof -o %PPID -x proactive-agent > /var/run/proactive-agent.pid
	fi
	echo
	;;
  stop)
	echo -n $"Shutting down proactive-agent: "
	if [ -e $AGENTHOME/cgroups/agent/tasks ] ; then
		rm -Rf $AGENTHOME/cgroups/agent
		umount -t cgroup -o memory proactive-agent $AGENTHOME/cgroups
	fi 
	killproc $prog
	RETVAL=$?
	[ $RETVAL -eq 0 ] && /bin/rm -f /var/lock/subsys/proactive-agent /var/run/proactive-agent.pid
	echo
	;;
  restart|reload)
        $0 stop
        $0 start
	RETVAL=$?
        ;;
  condrestart)
        if [ -f /var/lock/subsys/proactive-agent ]; then
                $0 stop
		$0 start
        fi
	RETVAL=$?
        ;;
  status)
        status proactive-agent
	RETVAL=$?
        ;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|condrestart|status}"
	exit 1
esac

exit $RETVAL
