#!/bin/sh

PACKAGE="proactive-agent"
INSTALLDIR="/opt/$PACKAGE"
PAUSER="proactive"
PAGROUP="proactive"

if [ -f "$INSTALLDIR/proactive-agent.log" ] 
then
   rm -f "$INSTALLDIR/proactive-agent.log*"
fi

deluser --quiet $PAUSER
groupdel $PAGROUP
