#!/bin/sh

PACKAGE="proactive-agent"

INSTALLDIR="/opt/$PACKAGE"

PAUSER="proactive"
PAGROUP="proactive"

if ! getent passwd $PAUSER >/dev/null; then
    adduser --quiet --system --no-create-home --home $INSTALLDIR --shell /bin/bash $PAUSER
fi

addgroup --system $PAGROUP
usermod -g $PAGROUP $PAUSER

chown -R $PAUSER:$PAGROUP $INSTALLDIR

chmod 755 /etc/init.d/$PACKAGE 

update-rc.d $PACKAGE defaults
invoke-rc.d $PACKAGE start
