#!/bin/sh

# Stop if any error
set -e 

assertexists(){
	# $1 File
	if [ -e "$1" ]
	then
		echo "File existence checked for: $1"
	else
		echo "ERROR, file does not exist: $1"
		exit 1
	fi
}

WHICHJAVA=`which java`

# Java configuration
JAVAPATH=$(readlink -e $WHICHJAVA | sed 's/bin\/java//g')

# TODO : Run a java Test
if [ "$?" = "1" ]
then
    # TODO : We can wget http://download.oracle.com/otn-pub/java/jdk/7u25-b15/jdk-7u25-linux-i586.tar.gz
    echo "ERROR: Please setup a Java >= 1.6 before installing this package"
    exit 1
fi

assertexists "$JAVAPATH/bin/java"
