Document: paagent
Title: Debian paagent Manual
Author: <insert document author here>
Abstract: This manual describes what paagent is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/paagent/paagent.sgml.gz

Format: postscript
Files: /usr/share/doc/paagent/paagent.ps.gz

Format: text
Files: /usr/share/doc/paagent/paagent.text.gz

Format: HTML
Index: /usr/share/doc/paagent/html/index.html
Files: /usr/share/doc/paagent/html/*.html
