.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PAAS "1" "October 23, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
paas \- System service which starts paagent_server
.SH DESCRIPTION
The paas system service starts the
.B 
paagent_server
at boot time. By default 
.B
paas
uses the 
.B
server-log4cxx
file placed in /etc/paagent for 
.B
paagent_server
logging configuration. The log is placed by default  in /var/log/paagent/server.log. ProActive is required to be installed for the services to run properly. A ProActive distribution can be downloaded from http://www.activeeon.com/community-downloads
 
.SH SEE ALSO
.BR paagent_server (1)
.BR paagent (1)
.BR paac (1)
.BR paagent_configuration (1)

.SH AUTHOR
paas was written by Vasile Jureschi <vjureschi@sophia.inria.fr>.
.PP
This manual page was written by Vasile Jureschi <vjuresch@sophia.inria.fr>,
and may be used by others.
