#!/bin/sh

PACKAGE="proactive-agent"
INSTALLDIR="/opt/$PACKAGE"
NODEDIR="/opt/proactive-node"
USER="proactive"
GROUP="proactive"

if ! getent passwd $USER >/dev/null; then
    useradd --system --no-create-home --home $INSTALLDIR --shell /bin/bash $USER
fi

chown -R $USER:$GROUP $INSTALLDIR
chown -R $USER:$GROUP $NODEDIR

chkconfig --add $PACKAGE
/sbin/service proactive-agent start
