#!/bin/bash
#
# /etc/rc.d/init.d/proactive-agent
#
# proactive-agent:	Starts the ProActive Agent 
# This script starts a proactive-agent under a dedicated account
#
# chkconfig: 2345 95 05
# description: Starts a ProActive agent
# processname: proactive-agent
# pidfile: /var/run/proactive-agent.pid
# config: /opt/proactive-agent/config.xml

### BEGIN INIT INFO
# Provides: 
# Required-Start: 
# Required-Stop: 
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 
# Short-Description: 
# Description:      
### END INIT INFO

# source function library
. /etc/rc.status
#. /etc/rc.d/init.d/functions

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0

SERVICENAME=proactive-agent

# default values
#################################33

PROG="/opt/proactive-agent/proactive-agent"
AGENTOPTS="--debug --daemon"
CONFFILE="/opt/proactive-agent/config.xml"

LOGFILE="/opt/proactive-agent/proactive-agent.log"
AGENTHOME="/opt/proactive-agent"

AGENTUSER="proactive"
AGENTGROUP="proactive"

# Set USE_CGROUP if cgreate is avaible
type -P cgcreate &>/dev/null && USE_CGROUP=1

# source the config
[ -r /etc/sysconfig/proactive-agent ] && . /etc/sysconfig/proactive-agent


function cgroup_mount() {
	mkdir -p $AGENTHOME/cgroups
	if [ ! -e $AGENTHOME/cgroups/tasks ] ; then
		mount -t cgroup -o memory proactive-agent $AGENTHOME/cgroups
		cgcreate -t $AGENTUSER:$AGENTGROUP -a $AGENTUSER:$AGENTGROUP -g memory:/proactive-agent
	fi 
}

function cgroup_umount() {
	  rmdir -- $AGENTHOME/cgroups/proactive-agent
	  umount $AGENTHOME/cgroups
}


RETVAL=0

case "$1" in
	start)
		echo -n "Starting ${SERVICENAME} services: "
	
		if [ "$USE_CGROUP" == "1" ] ; then
			cgroup_mount
		fi

		startproc \
		    -u $AGENTUSER
			-p /var/run/${SERVICENAME}.pid \
			$PROG --logFile $LOGFILE $AGENTOPTS $CONFFILE
		RETVAL=$?
		echo
		if [ $RETVAL -eq 7 ] ; then
			ps -ef | grep $PROG 2>/dev/null | grep python | awk '{print $2}' > /var/run/${SERVICENAME}.pid
			rc_status -v
		fi	
	;;
	stop)
		echo -n "Shutting down ${SERVICENAME} services: "

		if [ "$USE_CGROUP" == "1" ] ; then
			cgroup_umount
		fi

		killproc -p /var/run/${SERVICENAME}.pid python
		RETVAL=$?
		echo
		rc_status -v
		if [ $RETVAL -eq 0 ] ; then
			rm -f /var/run/${SERVICENAME}.pid
		fi
	;;
	restart)
		stop
		sleep 2
		start
	;;
	condrestart)
		if [ -f /var/lock/subsys/${SERVICENAME} ] ; then
			stop
			sleep 2
			start
		fi
	;;
	status)
		#status -p /var/run/${SERVICENAME}.pid ${SERVICENAME}
		/sbin/checkproc -p /var/run/${SERVICENAME}.pid python
		rc_status -v
		RETVAL=$?
	;;
	*)
		echo "Usage: $0 {start|stop|status|restart|condrestart}"
		exit 1
	;;
esac
