#!/bin/sh
#
# paagent  This shell script takes care of starting and stopping
#                  the paagent
#

# Source function library
#. /etc/rc.d/init.d/functions
. /lib/lsb/init-functions


### BEGIN INIT INFO
# Provides:          paac
# Required-Start:    $remote_fs $syslog 
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ProActive Linux agent daemon at boot time
# Description:       Enable service provided by ProActive Linux agent.
### END INIT INFO


# Do preliminary checks here, if any
#### START of preliminary checks #########

##### END of preliminary checks #######

# Constants
PAAC_OPTS="-l /etc/paagent/client-log4cxx -c /etc/paagent/config.xml "
PAAC_PID=/var/run/paac.pid
PAAC_EXEC=/usr/local/bin/paagent

# Handle manual control parameters like start, stop, status, restart, etc.

case "$1" in
  start)
    # Start daemons.
    log_daemon_msg "Starting paagent client daemon: "
    start-stop-daemon --start --background --quiet --oknodo --make-pidfile --pidfile $PAAC_PID --exec $PAAC_EXEC -- $PAAC_OPTS
    ;;
  stop)
    # Stop daemons.
    log_daemon_msg "Shutting down paagent client: "
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PAAC_PID; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;
  status)
	status_of_proc -p $PAAC_PID $PAAC_EXEC paagent && exit 0 || exit $?
    ;;
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac

exit 0
