#!/bin/sh                               
#                                       
# paagent  This shell script takes care of starting and stopping
#                  the paagent                                  
#                                                               
# chkconfig: 345 99 1                                           
# description: paagent daemon                                   
#                                                               
# processname: paagent                                          
# config: /etc/paagent/config.xml                               
# config: /etc/paagent/client-log4cxx                           
# pidfile: /var/run/paagent.pid                                 
#
# https://fedoraproject.org/wiki/Packaging:SysVInitScript#Fedora_SysV_Initscripts

### BEGIN INIT INFO
# Provides:          paac
# Required-Start:    $remote_fs $syslog 
# Required-Stop:     $remote_fs $syslog 
# Default-Start:     3 4 5              
# Default-Stop:      0 1 6              
# Short-Description: Start ProActive Linux agent daemon at boot time
# Description:       Enable service provided by ProActive Linux agent.
### END INIT INFO                                                     

# Source function library
. /etc/rc.d/init.d/functions

RETVAL=0

# Constants
PAAC_PRG="paagent"
PAAC_OPTS="-l /etc/paagent/client-log4cxx -c /etc/paagent/config.xml "
PAAC_LOCK=/var/lock/subsys/$PAAC_PRG                                  
PAAC_PID=/var/run/$PAAC_PRG.pid                                       
PAAC_EXEC=/usr/local/bin/$PAAC_PRG                                    
PAAC="$PAAC_EXEC $PAAC_OPTS"                                          

# Handle manual control parameters like start, stop, status, restart, etc.

start () {
    # Start daemons.

    echo  $"Starting paagent client daemon: "
    if [ -f $PAAC_LOCK ]; then               
        echo_failure $"Client already running"
        echo                                  
    else                                      
    daemon $PAAC&
    pidofproc $PAAC_PRG > $PAAC_PID
    RETVAL=$?
    if [ "$RETVAL" = 0 ]; then
        touch $PAAC_LOCK
        echo_success $"Paagent client start success"
        echo
    else
       rm -f $PAAC_LOCK
       echo_failure $"Error starting paagent client"
       echo
    fi
    fi
    return $RETVAL
}
stop () {
    # Stop daemons.
     echo -n $"Stopping $PAAC_PRG: "
     killproc $PAAC_PRG && rm -f $PAAC_LOCK $PAAC_PID
     RETVAL=$?
     echo
     return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
        status $PAAC_PRG
        RETVAL=$?
    ;;
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac

exit 0
