#!/bin/sh
#
# paagent_server  This shell script takes care of starting and stopping
#                  the paagent_server
#

# Source function library
#. /etc/rc.d/init.d/functions
. /lib/lsb/init-functions


### BEGIN INIT INFO
# Provides:          paas
# Required-Start:    $remote_fs $syslog 
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ProActive Linux agent dbus daemon at boot time
# Description:       Enable service provided by ProActive Linux dbus agent.
### END INIT INFO


# Do preliminary checks here, if any
#### START of preliminary checks #########

##### END of preliminary checks #######

# Constants
PAAS_OPTS="-l /etc/paagent/server-log4cxx"
PAAS_PID=/var/run/paas.pid
PAAS_EXEC=/usr/local/bin/paagent_server

# Handle manual control parameters like start, stop, status, restart, etc.

case "$1" in
  start)
    # Start daemons.
    log_daemon_msg "Starting paagent server daemon: "
    start-stop-daemon --start --background --quiet --oknodo --make-pidfile --pidfile $PAAS_PID --exec $PAAS_EXEC -- $PAAS_OPTS
    ;;
  stop)
    # Stop daemons.
    log_daemon_msg "Shutting down paagent server: "
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PAAS_PID; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;
  status)
	status_of_proc -p $PAAS_PID $PAAS_EXEC paagent_server && exit 0 || exit $?
    ;;
  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 1
esac

exit 0
